/**
 * Mock Data for LifeLink Testing
 * Contains 5 donors, 5 recipients, and 5 hospitals
 * Passwords are now stored as plain text (visible in Firestore)
 */

const mockData = {
  // ============================================
  // HOSPITALS (5)
  // ============================================
  hospitals: [
    {
      email: "city-general@hospital.com",
      password: "HospitalPass123",
      name: "City General Hospital",
      role: "hospital",
      phone: "+91-9876543210",
      hospitalName: "City General Hospital",
      address: "123 Medical Plaza, Downtown District",
      city: "Mumbai",
      license: "MGH2023001",
      licenseNormalized: "MGH2023001",
      createdAt: new Date("2025-01-15"),
      status: "approved",
    },
    {
      email: "apollo-hospital@hospital.com",
      password: "HospitalPass123",
      name: "Apollo Hospital",
      role: "hospital",
      phone: "+91-9876543211",
      hospitalName: "Apollo Hospital",
      address: "456 Health Tower, Business Park",
      city: "Delhi",
      license: "AHD2023002",
      licenseNormalized: "AHD2023002",
      createdAt: new Date("2025-01-20"),
      status: "approved",
    },
    {
      email: "fortis-healthcare@hospital.com",
      password: "HospitalPass123",
      name: "Fortis Healthcare",
      role: "hospital",
      phone: "+91-9876543212",
      hospitalName: "Fortis Healthcare",
      address: "789 Medical Center, Tech Park",
      city: "Bangalore",
      license: "FTH2023003",
      licenseNormalized: "FTH2023003",
      createdAt: new Date("2025-02-01"),
      status: "approved",
    },
    {
      email: "max-hospital@hospital.com",
      password: "HospitalPass123",
      name: "Max Hospital",
      role: "hospital",
      phone: "+91-9876543213",
      hospitalName: "Max Hospital",
      address: "321 Care Complex, Medical Zone",
      city: "Pune",
      license: "MXH2023004",
      licenseNormalized: "MXH2023004",
      createdAt: new Date("2025-02-05"),
      status: "approved",
    },
    {
      email: "sunrise-hospital@hospital.com",
      password: "HospitalPass123",
      name: "Sunrise Medical Hospital",
      role: "hospital",
      phone: "+91-9876543214",
      hospitalName: "Sunrise Medical Hospital",
      address: "654 Health Drive, Suburban Area",
      city: "Hyderabad",
      latitude: 17.385,
      longitude: 78.4867,
      license: "SMH2023005",
      licenseNormalized: "SMH2023005",
      createdAt: new Date("2025-02-10"),
      status: "approved",
    },
    {
      email: "care-hospital-pune@hospital.com",
      password: "HospitalPass123",
      name: "Care Multispecialty Hospital",
      role: "hospital",
      phone: "+91-9876543225",
      hospitalName: "Care Multispecialty Hospital",
      address: "42 Kondhwa Road, Pune",
      city: "Pune",
      latitude: 18.38,
      longitude: 73.92,
      license: "CMP2023006",
      licenseNormalized: "CMP2023006",
      createdAt: new Date("2025-02-15"),
      status: "approved",
    },
    {
      email: "medicore-pune@hospital.com",
      password: "HospitalPass123",
      name: "MediCore Advanced Hospital",
      role: "hospital",
      phone: "+91-9876543226",
      hospitalName: "MediCore Advanced Hospital",
      address: "87 Baner Road, Pune",
      city: "Pune",
      latitude: 18.6,
      longitude: 73.76,
      license: "MCA2023007",
      licenseNormalized: "MCA2023007",
      createdAt: new Date("2025-02-18"),
      status: "approved",
    },
    {
      email: "lifecare-hospital@hospital.com",
      password: "HospitalPass123",
      name: "LifeCare Hospital Pune",
      role: "hospital",
      phone: "+91-9876543227",
      hospitalName: "LifeCare Hospital Pune",
      address: "215 Hadapsar Road, Pune",
      city: "Pune",
      latitude: 18.4625,
      longitude: 73.9234,
      license: "LCP2023008",
      licenseNormalized: "LCP2023008",
      createdAt: new Date("2025-02-20"),
      status: "approved",
    },
  ],

  // ============================================
  // DONORS (5)
  // ============================================
  donors: [
    {
      email: "rajesh.kumar@email.com",
      password: "DonorPass123",
      name: "Rajesh Kumar",
      role: "donor",
      phone: "+91-9876543220",
      bloodGroup: "O+",
      location: "42 Residential Complex, Andheri West, Mumbai",
      available: true,
      createdAt: new Date("2025-01-10"),
      status: "approved",
      medicalHistory: [],
      completedDonations: 2,
      badges: [
        {
          threshold: 1,
          emoji: "🥉",
          title: "First Life Saver",
          description: "Completed your first donation",
        },
      ],
      medicalInfo: {
        age: 28,
        weight: 72,
        lastDonationDate: new Date("2025-02-15"),
        diseases: [],
        recentSurgery: false,
        surgeryDetails: null,
        recentIllness: false,
        illnessDetails: null,
        currentMedications: null,
        isPregnantOrNursing: false,
        eligibilityCheckedAt: new Date("2025-01-10"),
        eligible: true,
      },
    },
    {
      email: "priya.sharma@email.com",
      password: "DonorPass123",
      name: "Priya Sharma",
      role: "donor",
      phone: "+91-9876543221",
      bloodGroup: "A+",
      location: "78 Green Park Colony, New Delhi",
      available: true,
      createdAt: new Date("2025-01-12"),
      status: "approved",
      medicalHistory: [],
      completedDonations: 5,
      badges: [
        {
          threshold: 1,
          emoji: "🥉",
          title: "First Life Saver",
          description: "Completed your first donation",
        },
        {
          threshold: 5,
          emoji: "🥈",
          title: "5 Donations Hero",
          description: "Completed 5 donations",
        },
      ],
      medicalInfo: {
        age: 31,
        weight: 58,
        lastDonationDate: new Date("2025-02-20"),
        diseases: [],
        recentSurgery: false,
        surgeryDetails: null,
        recentIllness: false,
        illnessDetails: null,
        currentMedications: null,
        isPregnantOrNursing: false,
        eligibilityCheckedAt: new Date("2025-01-12"),
        eligible: true,
      },
    },
    {
      email: "amit.singh@email.com",
      password: "DonorPass123",
      name: "Amit Singh",
      role: "donor",
      phone: "+91-9876543222",
      bloodGroup: "B+",
      location: "234 Tech Park Avenue, Bangalore",
      available: false,
      createdAt: new Date("2025-01-15"),
      status: "approved",
      medicalHistory: [],
      completedDonations: 1,
      nextAvailableDate: new Date("2025-03-15"),
      badges: [
        {
          threshold: 1,
          emoji: "🥉",
          title: "First Life Saver",
          description: "Completed your first donation",
        },
      ],
      medicalInfo: {
        age: 26,
        weight: 68,
        lastDonationDate: new Date("2025-02-15"),
        diseases: [],
        recentSurgery: false,
        surgeryDetails: null,
        recentIllness: false,
        illnessDetails: null,
        currentMedications: null,
        isPregnantOrNursing: false,
        eligibilityCheckedAt: new Date("2025-01-15"),
        eligible: true,
      },
    },
    {
      email: "deepika.nair@email.com",
      password: "DonorPass123",
      name: "Deepika Nair",
      role: "donor",
      phone: "+91-9876543223",
      bloodGroup: "AB-",
      location: "156 Society Lane, Pune",
      available: true,
      createdAt: new Date("2025-01-18"),
      status: "approved",
      medicalHistory: [],
      completedDonations: 3,
      badges: [
        {
          threshold: 1,
          emoji: "🥉",
          title: "First Life Saver",
          description: "Completed your first donation",
        },
      ],
      medicalInfo: {
        age: 29,
        weight: 65,
        lastDonationDate: new Date("2025-02-10"),
        diseases: [],
        recentSurgery: false,
        surgeryDetails: null,
        recentIllness: false,
        illnessDetails: null,
        currentMedications: null,
        isPregnantOrNursing: false,
        eligibilityCheckedAt: new Date("2025-01-18"),
        eligible: true,
      },
    },
    {
      email: "vikram.patel@email.com",
      password: "DonorPass123",
      name: "Vikram Patel",
      role: "donor",
      phone: "+91-9876543224",
      bloodGroup: "O-",
      location: "89 Pearl Heights, Hyderabad",
      available: true,
      createdAt: new Date("2025-01-22"),
      status: "approved",
      medicalHistory: [],
      completedDonations: 0,
      badges: [],
      medicalInfo: {
        age: 23,
        weight: 70,
        lastDonationDate: null,
        diseases: [],
        recentSurgery: false,
        surgeryDetails: null,
        recentIllness: false,
        illnessDetails: null,
        currentMedications: null,
        isPregnantOrNursing: false,
        eligibilityCheckedAt: new Date("2025-01-22"),
        eligible: true,
      },
    },
  ],

  // ============================================
  // RECIPIENTS (5)
  // ============================================
  recipients: [
    {
      email: "anuj.mishra@email.com",
      password: "RecipientPass123",
      name: "Anuj Mishra",
      role: "recipient",
      phone: "+91-9876543230",
      aadhaarNumber: "1234-5678-9101",
      createdAt: new Date("2025-01-20"),
      status: "approved",
      medicalHistory: {
        bloodType: "O+",
        conditions: ["Anemia"],
      },
    },
    {
      email: "neha.dwivedi@email.com",
      password: "RecipientPass123",
      name: "Neha Dwivedi",
      role: "recipient",
      phone: "+91-9876543231",
      aadhaarNumber: "2345-6789-0112",
      createdAt: new Date("2025-01-25"),
      status: "approved",
      medicalHistory: {
        bloodType: "A+",
        conditions: ["Leukemia"],
      },
    },
    {
      email: "raman.joshi@email.com",
      password: "RecipientPass123",
      name: "Raman Joshi",
      role: "recipient",
      phone: "+91-9876543232",
      aadhaarNumber: "3456-7890-1123",
      createdAt: new Date("2025-02-02"),
      status: "approved",
      medicalHistory: {
        bloodType: "B+",
        conditions: ["Thalassemia"],
      },
    },
    {
      email: "sneha.verma@email.com",
      password: "RecipientPass123",
      name: "Sneha Verma",
      role: "recipient",
      phone: "+91-9876543233",
      aadhaarNumber: "4567-8901-1234",
      createdAt: new Date("2025-02-08"),
      status: "approved",
      medicalHistory: {
        bloodType: "AB-",
        conditions: ["Hemophilia"],
      },
    },
    {
      email: "suresh.reddy@email.com",
      password: "RecipientPass123",
      name: "Suresh Reddy",
      role: "recipient",
      phone: "+91-9876543234",
      aadhaarNumber: "5678-9012-3456",
      createdAt: new Date("2025-02-12"),
      status: "approved",
      medicalHistory: {
        bloodType: "O-",
        conditions: ["Post Surgical", "Recovery Phase"],
      },
    },
  ],

  // ============================================
  // EMERGENCY REQUESTS (Sample)
  // ============================================
  emergencyRequests: [
    {
      recipientId: "recipient_id_1", // Will be replaced with actual ID
      hospitalId: "hospital_id_1", // Will be replaced with actual ID
      patientName: "Patient One",
      bloodGroup: "O+",
      quantity: 2,
      urgencyLevel: "high",
      status: "active",
      admissionStatus: "admitted",
      createdAt: new Date("2025-02-20"),
      updatedAt: new Date("2025-02-20"),
    },
    {
      recipientId: "recipient_id_2",
      hospitalId: "hospital_id_2",
      patientName: "Patient Two",
      bloodGroup: "A+",
      quantity: 1,
      urgencyLevel: "medium",
      status: "pending-verification",
      admissionStatus: "pending",
      createdAt: new Date("2025-02-22"),
      updatedAt: new Date("2025-02-22"),
    },
    {
      recipientId: "recipient_care_pune",
      hospitalId: "care_multispecialty_pune",
      patientName: "Rajiv Malhotra",
      bloodGroup: "AB-",
      quantity: 3,
      urgencyLevel: "high",
      status: "active",
      admissionStatus: "admitted",
      createdAt: new Date("2025-02-25"),
      updatedAt: new Date("2025-02-25"),
    },
    {
      recipientId: "recipient_medicore_pune",
      hospitalId: "medicore_advanced_pune",
      patientName: "Priya Sengupta",
      bloodGroup: "AB-",
      quantity: 2,
      urgencyLevel: "high",
      status: "active",
      admissionStatus: "admitted",
      createdAt: new Date("2025-02-26"),
      updatedAt: new Date("2025-02-26"),
    },
    {
      recipientId: "recipient_lifecare_pune",
      hospitalId: "lifecare_hospital_pune",
      patientName: "Vikram Sharma",
      bloodGroup: "AB-",
      quantity: 4,
      urgencyLevel: "critical",
      status: "active",
      admissionStatus: "admitted",
      createdAt: new Date("2025-02-27"),
      updatedAt: new Date("2025-02-27"),
    },
  ],

  // ============================================
  // DONATIONS (Sample Completed)
  // ============================================
  donations: [
    {
      donorId: "donor_id_1", // Will be replaced
      recipientId: "recipient_id_1",
      hospitalId: "hospital_id_1",
      bloodGroup: "O+",
      quantity: 500,
      units: 1,
      status: "completed",
      donationDate: new Date("2025-02-15"),
      createdAt: new Date("2025-02-15"),
    },
    {
      donorId: "donor_id_2",
      recipientId: "recipient_id_2",
      hospitalId: "hospital_id_2",
      bloodGroup: "A+",
      quantity: 500,
      units: 1,
      status: "completed",
      donationDate: new Date("2025-02-20"),
      createdAt: new Date("2025-02-20"),
    },
  ],
};

module.exports = mockData;
